### ISSUE TITLE
suggestion: mention translation of (lepto/meso/platy)kurtosis

### ISSUE THREAD

**Issue by climatebrad** [learn-co-curriculum/dsc-skewness-and-kurtosis#1]
i.e.:
* "kurtosis" just is Greek for "bulging"
* "lepto" means "thin" (no common words use this, closest is **leptospirosis**, a disease caused by long, thin spiral bacteria)
![image](https://user-images.githubusercontent.com/6379550/68326974-7d937200-009a-11ea-82ce-1082310a5749.png)

* "meso" means "between" or "moderate" (**Mesopotamia** is between ("_meso_") the Tigris & Euphrates rivers "_potamos_")
![image](https://user-images.githubusercontent.com/6379550/68327014-913ed880-009a-11ea-992f-88b0fe992710.png)

* "platy" means "flat and wide" (a **platypus** has flat, wide feet.) 
![image](https://user-images.githubusercontent.com/6379550/68327071-a6b40280-009a-11ea-9cbf-b7cf6abe51ed.png)

**Comment by bpurdy-ds** [comment]
This is being phased out with v3.0.
