### ISSUE TITLE
First paragraph, last sentence (grammar)

### ISSUE THREAD

**Issue by Thegreatesthumphrey** [learn-co-curriculum/dsc-skewness-and-kurtosis#2]
Kurtosis defines whether a distribution is truly "normal" or whether it may have so-called "fatter" or "thinner" tails than you would observe when data ARE normally distributed.

Are should be is -

Im going to try and fix this error myself and submit it.

**Comment by bpurdy-ds** [comment]
This is being phased out with v3.0.
